app:
  name: finalApp
  version: 0.1
server:
  conn_type: tcp
  host: localhost
  port: 8080
  idle_timeout: 10
  read_timeout: 2
  write_timeout: 2
logger:
  level: 'local'
db:
  db_user: postgres
  db_password: postgres
  db_name: finalAppDB
  db_host: db
  db_port: 5432